### ISSUE TITLE
Show windows version dependency

### ISSUE THREAD

**Issue by bschuedzig** [felixrieseberg/ember-cli-windows#1]
Hi Felix,

thanks for you work! After giving this a try a found out, that it currently won't work with Windows 7 because of the call to "Set-MpPreference". 

https://technet.microsoft.com/en-us/library/dn433291.aspx

Do you know of any other way to archieve the result? Until then it might be good to add a compability list to the README.MD.

Best regards

**Comment by felixrieseberg** [comment]
Hey,

good point, thanks for the issue! Adding to the readme.md is a short-term solution, but we should find a way to make this work on 7. I'll take a look - leaving this open until closed.

Thanks again!

**Comment by felixrieseberg** [comment]
Turns out, we could in theory add a registry key to the exclusion list, but we'd have to change ownership of the registry path first - a pretty invasive operation. Instead, the tool will now print manual steps.

I also added a heavy recommendation for Windows 8/8.1/10 to the readme. Closing now.

**Comment by bschuedzig** [comment]
Found a small workaround by adding the path to the local gpo instead. It will show up in the Windows Defender UI (Options | Excluded files and folders) after that. Probably not the best way, but I thought I let you know anyway:

``` Powershell
function Add-WindowsDefenderExclusionsPolicy([string]$pathToAdd)
{                  
    $registryKey = "HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Exclusions\Paths" 

    $found = $False

    $items = Get-Item $registryKey

    Foreach ($name in $items.GetValueNames()) {
        if ([string]::Compare($name, $pathToAdd, $True) -eq 0) {
            # Path already added
            return $False
        }
    }

    Set-ItemProperty -Path $registryKey -Name $pathToAdd -Value 0 -Force
    Write-Host "Path added to defender exclusion list"

    # unsure if needed?
    #gpupdate | Out-Null

    return $True
}

Add-WindowsDefenderExclusionsPolicy "c:\example\path"
```

**Comment by felixrieseberg** [comment]
Awesome, thanks! Want to make a Pull Request?
