### ISSUE TITLE
ember-cli-windows command fails when there are spaces in path

### ISSUE THREAD

**Issue by timohermans** [felixrieseberg/ember-cli-windows#10]
Whenever there's a space in the path I get the error that it cannot recognize the first part of the folder with spaces in the name as a cmdlet, script, etc.

So to recreate, try to perform this in a folder with spaces in it

**Comment by mareksuscak** [comment]
Could you please post the exception details or a screenshot of powershell window? I'd like to know which of the two scripts has this problem.

**Comment by timohermans** [comment]
yes ofcourse:

Confirm: Do you want to proceed? (Y/N):  y
Configuring Defender
Configuring Search
Configuration Error:  C:\Users\PathWithSpace : The term 'C:\Users\PathWithSpace' is not recognized as the name of a cmdlet, function, script file, or operable

Configuration Error:  program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
- C:\Users\PathWithSpace AfterSpace\AppData\Roaming\npm\node_modules\ember-cli-windows\powersh ...
- ~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (C:\Users\PathWithSpace:String) [], CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException

Configuration Error:  C:\Users\PathWithSpace : The term 'C:\Users\PathWithSpace' is not recognized as the name of a cmdlet, function, script file, or operable

Configuration Error:  program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1

Configuration Error:  + C:\Users\PathWithSpace AfterSpace\AppData\Roaming\npm\node_modules\ember-cli-windows\powersh ...
- ~~~~~~~~~~~~~

Configuration Error:      + CategoryInfo          : ObjectNotFound: (C:\Users\PathWithSpace:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Configuration Error:

Windows Defender configured!
Finished Defender Configuration.
Windows Search configured!
Finished Search Configuration.

**Comment by mareksuscak** [comment]
Are you using ember-cli-windows-addon or are you invoking ember-cli-windows directly? I have tried it myself and I'm getting a different error:

```
Configure Windows for Ember-Cli Performace
If you continue, this tool will automate the configuration of Windows Defender and Windows Search
Confirm: Do you want to proceed? (Y/N):  y
Configuring Defender
Configuring Search
Configuration Error:  C:\Tools\NodeJs\node_modules\ember-cli-windows\powershell\setup-search.ps1 : A positional paramete
r cannot be found tha

Configuration Error:  t accepts argument 'dashboard'.
At line:1 char:1
+ C:\Tools\NodeJs\node_modules\ember-cli-windows\powershell\setup-search.ps1 -path ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [setup-search.ps1], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,setup-search.ps1


Windows Search configured!
Finished Search Configuration.
Configuration Error:  C:\Tools\NodeJs\node_modules\ember-cli-windows\powershell\setup-defender.ps1 : A positional parame
ter cannot be found t

Configuration Error:  hat accepts argument 'dashboard'.
At line:1 char:1
+ C:\Tools\NodeJs\node_modules\ember-cli-windows\powershell\setup-defender.ps1 -pa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [setup-defender.ps1], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,setup-defender.ps1


Windows Defender configured!
Finished Defender Configuration.
```

Anyway I know how to fix this, just asking if it's the same thing or there are multiple issues.

**Comment by timohermans** [comment]
I've tried this by invoking ember-cli-windows, so not the addon.

Your error doesn't ring a bell, but it's nice to know that you can fix it :).

**Comment by mareksuscak** [comment]
Done but we have to wait for @felixrieseberg to accept the pull request. If you want you can use mine fork or temporarily fix it directly in your globally installed ember-cli-windows package - it's as easy as [this](https://github.com/felixrieseberg/ember-cli-windows/pull/11/files).

**Comment by taraknaira** [comment]
Even I had the same issue, then I changed by directory to fix it from my side. Anyways better to fix this.

**Comment by timohermans** [comment]
Thanks @mareksuscak ! I don't know how to use a local npm package (yet), else I would've made a pull request myself :). 

Thanks again!

edit: @tarak162 I've done the same ;)

**Comment by taraknaira** [comment]
@temo44 for now you can simply copy paste the fix in your module (to the same file which is committed)
