### ISSUE TITLE
Handle spaces in paths when running the PowerShell scripts

### ISSUE THREAD

**Issue by petetnt** [felixrieseberg/ember-cli-windows#14]
I reported this to the felixrieseberg/ember-cli-windows-addon#5 but I made some effort today to solve that issue and turns out that the problem is with the `ember-cli-windows` bin itself.

[Line 16](https://github.com/felixrieseberg/ember-cli-windows/blob/master/bin/ember-cli-windows#L16) fails in the `bin` if the `scriptPath` includes spaces. I think that it's easily fixed by wrapping the path in single quotes as in [petetnt/ember-cli-windows/blob/master/bin/ember-cli-windows#L16](https://github.com/petetnt/ember-cli-windows/blob/master/bin/ember-cli-windows#L16)

```
var child = spawn('powershell.exe', ['-NoProfile', '-NoLogo', "'" + scriptPath + "'"),
```

edit: Actually the task wasn't that simple after all, it required quite a bit more work for it to function properly. The current variation is ugly, but seems to work correctly wrapping both the script path and the path to ignore:

```
var child = spawn('powershell.exe', ['-NoProfile', '-NoLogo', "& {& '"+ scriptPath + "'-path '" + dir + "'}"]), // jshint ignore:line

```

Any ideas on how to improve that are welcome, I am not that well versed in PowerShell.

**Comment by felixrieseberg** [comment]
Nice work, thank you! Do you want to make a quick pull request? That way you get the credit :) If not, I'm totally fine with putting it in myself.

**Comment by petetnt** [comment]
Sent you a PR :+1:
