### ISSUE TITLE
Spaces in path to ember app breaks install

### ISSUE THREAD

**Issue by jtsom** [felixrieseberg/ember-cli-windows#18]
If there's a space in the path to where the ember app is, running the ember-cli-windows command fails:

```
C:\Users\John Smith\Documents\simple>ember-cli-windows
Configure Windows for Ember-Cli Performace
If you continue, this tool will automate the configuration of Windows Defender and Windows Search
Confirm: Do you want to proceed? (Y/N):  y
Configuring Defender
Configuring Search
Configuration Error:  C:\Users\John : The term 'C:\Users\John' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that

Configuration Error:  the path is correct and try again.

Configuration Error:  C:\Users\John : The term 'C:\Users\John' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that

Configuration Error:  At line:1 char:1

Configuration Error:  the path is correct and try again.

Configuration Error:  + C:\Users\John Smith\AppData\Roaming\npm\node_modules\ember-cli-windows\power ...

Configuration Error:  At line:1 char:1

Configuration Error:  + ~~~~~~~~~~~~~

Configuration Error:  + C:\Users\John Smith\AppData\Roaming\npm\node_modules\ember-cli-windows\power ...

Configuration Error:      + CategoryInfo          : ObjectNotFound: (C:\Users\John:String) [], CommandNotFoundException

Configuration Error:  + ~~~~~~~~~~~~~

Configuration Error:      + FullyQualifiedErrorId : CommandNotFoundException

Configuration Error:      + CategoryInfo          : ObjectNotFound: (C:\Users\John:String) [], CommandNotFoundException

Configuration Error:

Configuration Error:      + FullyQualifiedErrorId : CommandNotFoundException

Configuration Error:

Windows Defender configured!
Finished Defender Configuration.
Windows Search configured!
Finished Search Configuration.
```

**Comment by jtsom** [comment]
Actually, looking closer, it's erroring on the path to it's own files

```
C:\Users\John Smith\AppData\Roaming\npm\node_modules\ember-cli-windows\power ...
```

**Comment by felixrieseberg** [comment]
Thanks for reporting - we clearly still have trouble with spaces in the oath. I'll take care of it!

**Comment by felixrieseberg** [comment]
Hey @jtsom, quick question - are you using the latest version of `ember-cli-windows`? Because looking at our code, the PR from @petetnt _should_ have fixed this. If you are, what version of Windows are you on?

**Comment by jtsom** [comment]
I just installed it this morning, via npm install -g ember-cli-windows, so I assume it's the latest?

Also this is on Windows 8.1.

**Comment by petetnt** [comment]
I just checked it out, the [npm package](https://www.npmjs.com/package/ember-cli-windows) hasn't been updated yet. Could you push the latest version there @felixrieseberg (and bump the version on `package.json` to `1.3.3.`?

Meanwhile @jtsom you can install `ember-cli-windows` directly from the master with `npm install felixrieseberg/ember-cli-windows`

**Comment by jtsom** [comment]
Hmmm..I just looked at the package.json for the installed version, and it's showing:

"version": "1.3.2", which is what is showing in this repo

**Comment by petetnt** [comment]
Yeah, it needs a version bump too. You should see this line:

```
var child = spawn('powershell.exe', ['-NoProfile', '-NoLogo', "& {& '"+ scriptPath + "' -path '" + dir + "'}"]), // jshint ignore:line
```

instead of 

```
var scriptPath = path.resolve(__dirname, '../powershell/setup-search.ps1') + ' -path "' + dir + '"',
```

on `bin/ember-cli-windows`. I created another issue #19 to track the `npm` update.

**Comment by jtsom** [comment]
Ok, installing directly from felixrieseberg/ember-cli-windows (and running the command to allow execution) seems to have worked. (Also, I was just using a cmd window, not Powershell)
