### ISSUE TITLE
Build super slow after windows update

### ISSUE THREAD

**Issue by medokin** [felixrieseberg/ember-cli-windows#25]
After todays updates, the build is slower than ever.
![image](https://cloud.githubusercontent.com/assets/456683/10102145/1aea15bc-639d-11e5-971f-a2f2e9d958ed.png)

Any Ideas?

**Comment by billpull** [comment]
Just in general performance seems really bad on windows 10

**Comment by medokin** [comment]
The question is, if it can be resoved by a system configuration or ember-cli...

**Comment by felixrieseberg** [comment]
I haven't seen slower builds compared to Windows 8 - anything special about y'all machines? Are you using the latest of Node/NPM/etc?

**Comment by medokin** [comment]
Indexer and Security essentials have ignored every option. Works fine after reinstalling windows.
