### ISSUE TITLE
Different errors while running the tool

### ISSUE THREAD

**Issue by sedovalx** [felixrieseberg/ember-cli-windows#3]
I can't manage to make it work. First of all one need unrestricted PowerShell execution policy to run the scripts or one get:

> - CategoryInfo          : Security error: (:) [], PSSecurityException
> - FullyQualifiedErrorId : UnauthorizedAccess

I set the policy:

```
Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process
```

and get 

> C:\Users\Aleksandr\AppData\Roaming\npm\node_modules\ember-cli-windows\powershell\setup-defender.ps1:85 :5
> -     Set-MpPreference -ExclusionPath $path
> -     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft...FT_MpPreference) [Set-MpPreference], CimException
>   - FullyQualifiedErrorId : HRESULT 0x800106ba,Set-MpPreference

The $path variable is equal to "E:\Scala\taxi\sources\client" folder. I can see it from the output

> Removing E:\Scala\taxi\sources\client from Windows Defender's Eye

 The folder exists for sure. Whet to do next? 
Thank you!

p.s.:
OS: Windows 8.1
User has administrative rights

**Comment by sedovalx** [comment]
OS: Windows 8.1
User has administrative rights

**Comment by felixrieseberg** [comment]
Interesting, thank you so much for the report. If you're having these issues, someone else is too.

Can you do me a favor and run `Set-MpPreference -ExclusionPath E:\Scala\taxi\sources\client` from PowerShell? I'd love to see what (if any) error appears if you run it yourself.

**Comment by felixrieseberg** [comment]
Actually, it appears that the error indicates trouble with Windows Defender. We're calling Windows Defender, so it makes sense that the tool wouldn't work if Defender doesn't work. There's a bunch of resources and I'd like for you to try them:

1) A "Fixit" thing from Microsoft, where you just click a button and the error is supposed to just disappear (http://support.microsoft.com/en-us/kb/931849)
2) A small blog post on how to fix Windows Defender with the error code you gave me (http://www.thewindowsclub.com/windows-defender-error-code-0x800106ba-application-failed-to-initialize)
3) A short YouTube Video with instructions in case the service isn't running (https://www.youtube.com/watch?v=8xGG5_KYOZQ)

**Comment by sedovalx** [comment]
Thank you for your response. Indeed the Defender is disabled on my machine. So I don't need to set exclusion list for it. Therefore execeution of setup-search.ps1 should be enogh to setup the folder. I've done it already. The build of almost empty application speeded up to 6-7 sec (from 13-14 sec). It's better but not ideal :)

**Comment by felixrieseberg** [comment]
Good, nice to hear! If Defender isn't running in the first place, there's no speed to be gained by disabling it for Ember :) I'll close this now, although we should probably check if defender is running.

**Comment by stefek99** [comment]
I'm using Powershell as admin:

```
PS C:\b\devportal> ember-cli-windows
Configure Windows for Ember-Cli Performace
If you continue, this tool will automate the configuration of Windows Defender a
nd Windows Search
Confirm: Do you want to proceed? (Y/N):  Y
Configuring Defender
Configuring Search
Removing file:///C:\b\devportal\tmp\* from Search Index


Removing C:\b\devportal from Windows Defender's Eye


Done

Windows Search configured!
Finished Search Configuration.
Configuration Error:  Set-MpPreference : Operation failed with the following err
or: 0x800106ba.

Configuration Error:  Operation: MpPreference. Target: ConfigListExtension.
At C:\Users\a-miste\AppData\Roaming\npm\node_modules\ember-cli-windows\powershe
ll\setup-defender.ps1:98 char:5
+     Set-MpPreference -ExclusionPath $path
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\
   ...FT_MpPreference) [Set-MpPreference], CimException
    + FullyQualifiedErrorId : HRESULT 0x800106ba,Set-MpPreference


Done

Windows Defender configured!
Finished Defender Configuration.
```

When I set the policy I'm getting same error...

**Comment by felixrieseberg** [comment]
Hey Stefek99, according to the error, you either disabled Windows Defender or `Error Code 0x800106ba: The systems license has expired. Your logon request is denied.`

Can you confirm that you're running a fully licensed version of Windows and that defender is running in the first place? Because the script apparently instructed your system in the right way, but Windows rejected the instruction...

**Comment by stefek99** [comment]
http://lmgtfy.com/?q=is+windows+defender+running

I cannot tell if I have Windows Defender installed and running.

Is `ember-cli-windows` doing anything other than disabling Windows Defender?

Either way some check and more helpful message would be nice.

**Comment by felixrieseberg** [comment]
Hit `Start`, search for `Defender`. It'll tell you. This tool also disables the search index for Ember's temp folders, but that operation will run even if the defender stuff gives you errors.

![](http://images.techhive.com/images/article/2012/12/windows-defender-settings-100017384-large.jpg)
