### ISSUE TITLE
doesn't appear to support multiple options

### ISSUE THREAD

**Issue by kellyselden** [felixrieseberg/ember-cli-windows#30]
I tried running both `defender` option with the `headless` option, and I was still getting an error in the `setup-search.ps1` script. Taking off the `headless` param worked, but then gave me a prompt.

**Comment by felixrieseberg** [comment]
Well, that's obviously dumb of me. I'll fix that.

**Comment by felixrieseberg** [comment]
Closed in 2.1.0!

**Comment by kellyselden** [comment]
Thanks Felix.
