### ISSUE TITLE
Always warns about running without elevated rights.

### ISSUE THREAD

**Issue by DanChadwick** [felixrieseberg/ember-cli-windows#31]
I have a Windows 10 laptop and a Windows 7 desktop. Using `ember-cli-windows` worked great configuring the Windows 10 laptop. It builds quickly and does not warn of not having elevated rights. The Windows 7 machine, however, always warns about not having elevated rights. I have tried:
1. Running git-bash versus windows powershell.
2. Running as administrator (which I always do) via right-click
3. Configuring the shortcut to run as administrator.
4. Running `Set-ExecutionPolicy Unrestricted -scope Process`
5. Of course, running `ember-cli-windows`
6. Disabling User Access Control.
7. I run from "an" administrator account, but apparently there is a hidden superuser administrator account that I am not using (and am not keen to use due to having to reinstall lots of stuff for that user).

In addition and probably unrelated, when I load the page in the browser, the throbber continues to spin and the livereload server never completes the way it does on the Windows 10 laptop.

I have no idea what useful information I can give you. My build times are about 50 seconds from starting `ember s` and about 8-10 seconds for rebuilding after a file change. Any clue what I might try next?

**Comment by felixrieseberg** [comment]
Hm, that's weird - we just test if PowerShell can verify you as an Administrator. That being said, I heavily recommend Windows 10, or at least Windows 8.1. Windows 7 was released years before Ember was invented, and many years before Ember Cli became a thing. I don't actively develop this for Windows 7 and rely on Pull Requests to make it work - if you find what's wrong, I'll gladly include any fixes.

To help you out, we could add an option that overrides the administrator check and attempts to execute no matter what. I can add that tomorrow - would that help?

**Comment by DanChadwick** [comment]
@felixriesenberg -- sure. Worth trying. How exactly to you verify that the user is an Administrator? Is there any debugging info that I can give you that would be helpful?

I also wonder if the odd behavior of livereload not completing might be somehow related. Updating to Windows 10 is an option, but I'm not much of a fan. :)

**Comment by DanChadwick** [comment]
@felixrieseberg - Thank you for the Windows OS version tip. I upgraded 7 -> 10 and both the LiveReload and complaining about not having elevated rights problems went away (without making any other changes). So, please don't make that special version on my account. And thank you for work contribution to the Ember Windows community. :100:

**Comment by felixrieseberg** [comment]
Happy to hear that things are working for you now :clap:!
