### ISSUE TITLE
Promotion outside ember community

### ISSUE THREAD

**Issue by philipbjorge** [felixrieseberg/ember-cli-windows#34]
Hey Felix,

I've been using this tool to great effect with a lot of non-ember related projects on Windows:
- Speeding up npm installs
- Speeding up bulk importing of data into elasticsearch (import times went from 30->10 minutes!)
- Speeding up VS builds

Have you given any thought to renaming this project or promoting it to broader circles?

**Comment by felixrieseberg** [comment]
Great point - I could in theory just break the "ignore these files" logic out into its own module and have ember-cli-windows consume it. It's on the to-do list now ;-)
