### ISSUE TITLE
Give useful error if Defender isn't enabled

### ISSUE THREAD

**Issue by felixrieseberg** [felixrieseberg/ember-cli-windows#4]
If defender isn't enabled, we get a pretty nasty and confusing error (`cimexception` with code `0x800106ba`). There should probably be a more useful error reporting here.

**Comment by mareksuscak** [comment]
You could do that by checking `DisableAntiSpyware` value which is under the following registry key:

`HKLM\SOFTWARE\Microsoft\Windows Defender`

I'm using Win 7 SP1 x64 so not quite sure about x86 and Win 8, Win 8.1 and Win10 but I guess it's the same. 

Then there's also `DisableRealtimeMonitoring` value under:

`HKLM\SOFTWARE\Microsoft\Windows Defender\Real-Time Protection` so I'm not sure if the off state also causes the error.

UPDATE: And be careful when not running under user account without the admin privilege - it might be required to read that reg. key.

**Comment by felixrieseberg** [comment]
Good pointers, thanks for those!
