### ISSUE TITLE
No improvement in Angular Cli commands execution speed on Windows 10 x64

### ISSUE THREAD

**Issue by micobarac** [felixrieseberg/ember-cli-windows#44]
I am using the latest Angular Cli v. 7 on Windows 10 x64.
My computer has 8GB of RAM, SSH fast hard drive, fast i7 Intel CPU.
So, the hardware is not an issue.

Angular Cli, which is built on top Ember is so painfully slow, even with the simplest possible Hello World application.

I have excluded the project folder from antivirus and disabled the Windows Defender.

Running Ember Cli Windows configured Search Service, complaining that it couldn't have configured Windows Defender as it was already turned off, which was ok.

I have restarted Angular Cli with `yarn start`, but with no speed improvement at all :(.

**Comment by locks** [comment]
I don't think ng-cli uses any of the original code anymore!
