### ISSUE TITLE
Configuration Error:  Join-Path : Cannot bind argument to parameter 'Path' because it is null.

### ISSUE THREAD

**Issue by taraknaira** [felixrieseberg/ember-cli-windows#5]
I am getting below error after installing and executing ember-cli-windows. Please suggest the solution. 

Configuration Error:  At C:\Users*****\AppData\Roaming\npm\node_modules\ember-cli-windows\powershell\setup-search.ps1:23 char:26
- Add-Type -Path (Join-Path <<<<  $PSScriptRoot "Microsoft.Search.Interop.dll")
  - CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
  - FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand

Configuration Error:  New-Object : Cannot find type [Microsoft.Search.Interop.CSearchManagerClass]: make sure the assembly containing this type is loa
ded.

**Comment by felixrieseberg** [comment]
Hey Tarak, thanks for reporting this. I'm sure we can fix this, as the script is complaining about not finding the Windows Search DLL. Can you do me a quick favor and tell me about the following:
- If you open up C:\Users*****\AppData\Roaming\npm\node_modules\ember-cli-windows\powershell\, do you see a DLL?
- Which version of Windows are you running?

Thanks!

**Comment by taraknaira** [comment]
I can see Microsoft.Search.Interop.dll exists in that directory. For a note, I do not have admin privileges to my system. Is this something to worry about. In my system, windows defender is OFF and we do have an antivirus client which we can configure at our end.

**Comment by felixrieseberg** [comment]
Hm, you shouldn't need Admin privileges. It's possible that your Admin locked down more rights, keeping you from even using the Search feature - which version of Windows are you running on?

**Comment by taraknaira** [comment]
Sorry I missed that part. I am using Windows 7 machine.

**Comment by mareksuscak** [comment]
It might be that you have an older powershell than required to use `$PSScriptRoot`. Based on [this SO answer](http://stackoverflow.com/a/3667376/596625) `$PSScriptRoot` was introduced in Powershell 3 so if you have a version older than that it won't work and therefore we could fix that by using a different way of getting executing script path.

@tarak162 Would you mind checking your powershell version by invoking either `Get-Host` or `$PSVersionTable.PSVersion` and paste the output here in the comment? That would really help us in getting it working properly for you.

**Comment by mareksuscak** [comment]
That said, a quick workaround for you would be to upgrade to newer Windows Management Framework by following a link in the [WMF download matrix](http://social.technet.microsoft.com/wiki/contents/articles/21016.how-to-install-windows-powershell-4-0.aspx) and in the meantime we might fix that for older versions.

**Comment by taraknaira** [comment]
Thanks for looking into this. I was on vacation and could not back to you. Here is my powershell info. Looks like I have version 2 installed.

![powershell_vesrion](https://cloud.githubusercontent.com/assets/6814268/6819034/7622f294-d2e0-11e4-8082-f6c9176e9cff.png)

**Comment by taraknaira** [comment]
I can even try upgrading newer powershell version but that needs installing other softwares along with new powershell. This needs sys admin's approval. Is there any work around in the code to get it fixed.

**Comment by mareksuscak** [comment]
@tarak162 Could you please clone my fork, switch to issue-5 branch and try the script if it now works on Powershell 2? I have Powershell 4 and don't want to install the older version myself but it should work as is. Thanks. In the meantime I'll send a pull request.

**Comment by taraknaira** [comment]
@mareksuscak Looks like that error is gone now. But do we need admin privileges to run this? It is opening powershell window and asking for admin id, pwd.

**Comment by mareksuscak** [comment]
Yes, you need admin privileges to change Windows Search settings - you anyway need them to make ember-cli builds faster because without admin privileges you probably don't have Create Symlink permissions (see [here](http://www.ember-cli.com/#symlinks-on-windows) for further info) and also you cannot change the local computer policy to add this permission to your account without privilege elevation.

@felixrieseberg So my fix worked on both Powershell 2 (confirmed by @tarak162) and Powershell 4 (tested by me) - you can close this issue and accept my pull request I guess.

**Comment by taraknaira** [comment]
Below is the complete process and logging

Configure Windows for Ember-Cli Performace
If you continue, this tool will automate the configuration of Windows Defender and Windows Search
Confirm: Do you want to proceed? (Y/N):  Y
Configuring Defender
Configuring Search
Removing file:///e:\workspace\em-cli\tmp* from Search Index

Configuration Error:  Exception calling "AddUserScopeRule" with "4" argument(s): "Value does not fall within the expected range."

Configuration Error:  At C:\Users****\AppData\Roaming\npm\node_modules\ember-cli-windows\powershell\setup-search.ps1:41 char:27
- $crawlman.AddUserScopeRule <<<< ($tmpPath,$false,$true,$null)
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : DotNetMethodException

Done

Windows Search configured!
Finished Search Configuration.

*****_<here pops up an window which asks for admin permissions>**_**

Configuration Error:  Start-Process : This command cannot be executed due to the error: The operation was canceled by the user.

Configuration Error:  At C:\Users****\AppData\Roaming\npm\node_modules\ember-cli-windows\powershell\setup-defender.ps1:64 char:22

Configuration Error:  +         Start-Process <<<<  PowerShell.exe -Verb Runas -WorkingDirectory $pwd -ArgumentList $argList

Configuration Error:      + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

Configuration Error:

Windows Defender configured!
Finished Defender Configuration.

**Comment by taraknaira** [comment]
Thanks, So what's the advantage of using this for a windows user who does not have admin privilege?

**Comment by mareksuscak** [comment]
@tarak162 I believe you are on Windows 7. There's been this error in the script in previous versions but it should be fixed already in ember-cli-windows 1.3.1 so ensure you have the latest version. 

Please note that if you are using ember-cli-windows-addon it hasn't been updated yet to use ember-cli-windows 1.3.1 - instead it is still using 1.3.0 which didn't have this issue fixed. So your best bet is to install ember-cli-windows globally and use it without addon for now. @felixrieseberg Could you update the dependency?

Regarding your question - there's this advantage that you don't have to configure Windows Search and Defender by hand each time you create new ember application. I recommend to ask your employer for admin privileges because usually developer cannot live without them - I know what I'm talking about, believe me.

**Comment by taraknaira** [comment]
Thanks @mareksuscak . Finally I am able to run ember-cli-windows with the help of admin privileges but I did not see any improvements in my build times. Below are my build times

Build successful - 315841ms.

Slowest Trees                  | Total
-------------------------------+----------------
TreeMerger (stylesAndVendor)   | 64257ms
ES6: App Tree                  | 37963ms
TreeMerger (appAndDependencies) | 30032ms
CustomStaticCompiler           | 29100ms
TreeMerger                     | 29070ms

file changed templates\member-benefits.hbs

Build successful - 267123ms.

Slowest Trees                  | Total
-------------------------------+----------------
CustomStaticCompiler           | 46051ms
TreeMerger (appAndDependencies) | 30124ms
TreeMerger (stylesAndVendor)   | 20078ms
TreeMerger (ExternalTree)      | 16821ms
ES6: App Tree                  | 13852ms

file changed templates\member-benefits.hbs

Build successful - 203747ms.

Slowest Trees                  | Total
-------------------------------+----------------
CustomStaticCompiler           | 18528ms
TreeMerger (appAndDependencies) | 15597ms
Babel                          | 12380ms
ES6: App Tree                  | 12063ms
TreeMerger (stylesAndVendor)   | 11882ms
ES3SafeFilter                  | 11230ms
TreeMerger (ExternalTree)      | 10753ms

file changed templates\member-benefits.hbs

Build successful - 221056ms.

Slowest Trees                  | Total
-------------------------------+----------------
Funnel: App JS Files           | 31896ms
ES6: App Tree                  | 27292ms
TreeMerger                     | 20733ms
CustomStaticCompiler           | 18259ms
TreeMerger (appAndDependencies) | 16584ms

**Comment by taraknaira** [comment]
Closing this issue since the error is fixed. But my build times are not affected.

**Comment by mareksuscak** [comment]
@tarak162 make sure to run powershell in which you are running `ember serve` or `ember build` as an administrator. There's a good chance this is due to not being able to create symlinks which broccoli asset builder uses. Like I said [check out this](http://www.ember-cli.com/#symlinks-on-windows).

![powershell-admin](https://cloud.githubusercontent.com/assets/613647/6823777/a38b2818-d2eb-11e4-8fc4-621795edbaa8.png)

**Comment by taraknaira** [comment]
@mareksuscak I made symlink changes but did not see any improvement. 

Your suggestion to run ember build/serve as an admin worked perfectly. Now it has reduced to nearly 10 times lower. This is really a good suggestion. Thanks a lot. Looks like all these are tightly related to admin privileges. It would be better to have admin account on windows or use linux machine. 

Below are my new build times

file added templates\member-benefits.hbs___jb_bak___
file deleted templates\member-benefits.hbs___jb_bak___
file changed templates\member-benefits.hbs

Build successful - 36162ms.

Slowest Trees                  | Total
-------------------------------+----------------
Funnel: App JS Files           | 6596ms
TreeMerger (appAndDependencies) | 5113ms
ES6: App Tree                  | 4637ms
JSHint app- QUnit              | 2473ms
JSHint tests- QUnit            | 2076ms
Babel                          | 1893ms

file changed routes\application.js

Build successful - 42800ms.

Slowest Trees                  | Total
-------------------------------+----------------
ES6: App Tree                  | 6813ms
Funnel: App JS Files           | 6612ms
TreeMerger (appAndDependencies) | 4220ms
Babel                          | 3244ms
JSHint app- QUnit              | 2676ms
Concat: App                    | 2184ms

file changed routes\application.js

Build successful - 32240ms.

Slowest Trees                  | Total
-------------------------------+----------------
Funnel: App JS Files           | 5370ms
TreeMerger (appAndDependencies) | 4913ms
JSHint app- QUnit              | 3176ms
ES6: App Tree                  | 2325ms
